from socpuppet.detections.sentinel_azure_active_directory.audit_log_role_management import *
from socpuppet.detections.sentinel_azure_active_directory.audit_log_policy import *
from socpuppet.detections.sentinel_azure_active_directory.audit_log_user_management import *
from socpuppet.detections.sentinel_azure_active_directory.audit_log_groupmanagement import *